apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "userGroupOperator.name" . }}
  namespace: {{ include "userGroupOperator.namespaceName" . }}
  labels:
    {{- include "userGroupOperator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
